# keycloak-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: shopizerecomm/keycloak:4.0.1.2
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KC_DB
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_DB
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_DB_PASSWORD
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_DB_URL
            - name: KC_FEATURES
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KC_FEATURES
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HTTP_RELATIVE_PATH
              value: /keycloak
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME
              value: keycloak
            - name: KC_HOSTNAME_PATH
              value: /keycloak