apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-common-env
  namespace: default
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-opentelemetry-collector.monitoring.svc.cluster.local:4318"
  OTEL_EXPORTER_OTLP_PROTOCOL: "http/protobuf"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=local,service.namespace=shopizer"
