apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchants
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchants
  template:
    metadata:
      labels:
        app: merchants
    spec:
      initContainers:
        - name: download-otel-agent
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              curl -L -o /otel/opentelemetry-javaagent.jar \
              https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.14.0/opentelemetry-javaagent.jar
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
      containers:
        - name: merchants
          image: localhost:5001/shopizer-merchants:latest
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1000m
          volumeMounts:
            - name: otel-agent
              mountPath: /otel
          envFrom:
            - configMapRef:
                name: otel-common-env
          env:
            - name: APPLICATION_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_HOST

            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: APPLICATION_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_NAME
            - name: APPLICATION_DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_USER
            - name: APPLICATION_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_PASSWORD
            - name: APPLICATION_REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_REDIS_HOST
            - name: APPLICATION_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_ISSUER_URL
            - name: APPLICATION_SERVICE_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_SERVICE_ISSUER_URL
            - name: APPLICATION_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_CLIENT_ID
            - name: APPLICATION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_CLIENT_SECRET
            - name: APPLICATION_CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_CRYPTO_KEY

            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:+UseContainerSupport
                -Xmx768m
                -XX:MaxRAMPercentage=45.0
                -XX:MaxMetaspaceSize=256m
                -XX:ReservedCodeCacheSize=64m
                -XX:MaxDirectMemorySize=16m
                -Xss512k
                -javaagent:/otel/opentelemetry-javaagent.jar
                -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
          ports:
            - containerPort: 8080
          #           - containerPort: 5005   # debug port
      volumes:
        - name: otel-agent
          emptyDir: {}
