apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  APPLICATION_DB_PASSWORD: pass
  APPLICATION_DB_HOST: postgres
  APPLICATION_DB_NAME: shop
  APPLICATION_DB_USER: user
  APPLICATION_REDIS_HOST: redis
  APPLICATION_DB_PORT: "5432"
  APPLICATION_ISSUER_URL: http://keycloak/keycloak/realms/shopizer
  APPLICATION_SERVICE_ISSUER_URL: http://keycloak/keycloak/realms/shopizer
  APPLICATION_CLIENT_ID: shopizer
  APPLICATION_CLIENT_SECRET: bRTFYUDw1WPd74PTfvvXdUeQzrRiYUqY
  APPLICATION_SERVICE_ISSUER_REALM: shopizer
  OPENAI_API_KEY: __OPENAPI_KEY__
