apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: localhost:5001/shopizer-users:latest
          ports:
            - containerPort: 8080
            - containerPort: 5007
          env:
            - name: APPLICATION_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_HOST
            - name: APPLICATION_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_NAME
            - name: APPLICATION_DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_USER
            - name: APPLICATION_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_DB_PASSWORD
            - name: APPLICATION_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_ISSUER_URL
            - name: APPLICATION_SERVICE_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_SERVICE_ISSUER_URL
            - name: APPLICATION_SERVICE_ISSUER_REALM
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_SERVICE_ISSUER_REALM
            - name: APPLICATION_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_CLIENT_ID
            - name: APPLICATION_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_CLIENT_SECRET
            - name: APPLICATION_CRYPTO_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: APPLICATION_CRYPTO_KEY
            - name: MERCHANT_URL
              value: http://merchants
              #url to call from backend services
            - name: AUTH_URL
              value: http://keycloak.default.svc.cluster.local/keycloak
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:+UseContainerSupport
                -XX:MaxRAMPercentage=75.0
                -Xss512k
                  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5007